### ISSUE TITLE
Question about `just all` test

### ISSUE THREAD

**Issue by danellecline** [mbari-org/pbp#30]
Hi @carueda 

Per the DEVELOPMENT instructions

```
**NOTE**: Before committing/pushing any changes, make sure to run:
j all
```

Which runs successfully after my code changes, but upon check-in, the github action is failing with ruff formatting errors.
See https://github.com/mbari-org/pbp/actions/runs/10565013072 for an example.

Should the `format` or `format-check` be included in the `just all` recipe?

**Comment by carueda** [comment]
strange

- `j all` already includes `format` (via `dev`)
- that didn't happen to me. When I did `j all` it included the `format` step, and then I pushed the updated file.
-

**Comment by danellecline** [comment]
Huh. that is strange.  When I run `j all` I now see

```
/D/c/pbpkeep (main 👍  ) dcline@ADA.shore.mbari.org🐠  j all                                                                                                                                                                                                                                                                                                                                                                                         (pbp)  Mon Aug 26 12:33:59 2024
poetry run mypy .
pbp/plotting.py:125: error: Argument 2 to "annotate" of "Axes" has incompatible type "tuple[ndarray[Any, dtype[signedinteger[Any]]], int]"; expected "tuple[float, float]"  [arg-type]
pbp/plotting.py:127: error: Argument 2 to "annotate" of "Axes" has incompatible type "tuple[ndarray[Any, dtype[signedinteger[Any]]], int]"; expected "tuple[float, float]"  [arg-type]
pbp/plotting.py:134: error: No overload variant of "add_axes" of "FigureBase" matches argument type "list[Any]"  [call-overload]
pbp/plotting.py:134: note: Possible overload variants:
pbp/plotting.py:134: note:     def add_axes(self, ax: Axes) -> Axes
pbp/plotting.py:134: note:     def add_axes(self, rect: tuple[float, float, float, float], projection: str | None = ..., polar: bool = ..., **kwargs: Any) -> Axes
pbp/plotting.py:140: error: No overload variant of "add_axes" of "FigureBase" matches argument types "Bbox", "bool"  [call-overload]
pbp/plotting.py:140: note: Possible overload variants:
pbp/plotting.py:140: note:     def add_axes(self, ax: Axes) -> Axes
pbp/plotting.py:140: note:     def add_axes(self, rect: tuple[float, float, float, float], projection: str | None = ..., polar: bool = ..., **kwargs: Any) -> Axes
Found 4 errors in 1 file (checked 32 source files)
error: Recipe `mypy` failed on line 285 with exit code 1
~
```

Perhaps there is something mangled in my environment.

**Comment by carueda** [comment]
Yes, maybe retry the `setup` or `update-types` recipes(?)

This is how the output of `j all` looks like for me right now

```
❯ j all
poetry run mypy .
Success: no issues found in 35 source files
poetry run pytest
============================= test session starts =============================
platform darwin -- Python 3.11.9, pytest-7.4.4, pluggy-1.5.0
rootdir: /Users/carueda/github/mbari-org/soundscape-repos/pbp
configfile: pyproject.toml
testpaths: tests
plugins: syrupy-4.6.1, cov-4.1.0
collected 16 items

tests/test_file_helper.py .                                             [  6%]
tests/test_json_support.py ...                                          [ 25%]
tests/test_meta_generator.py .....                                      [ 56%]
tests/test_metadata.py ...                                              [ 75%]
tests/test_misc.py ..                                                   [ 87%]
tests/test_simpleapi.py ..                                              [100%]

============================== warnings summary ===============================
tests/test_meta_generator.py::test_soundtrap_generator_local
  /Users/carueda/Library/Caches/pypoetry/virtualenvs/mbari-pbp-7GDH8Njx-py3.11/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py:1561: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
    ax.set_xlim(left, right)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
--------------------------- snapshot report summary ---------------------------
10 snapshots passed.
================== 16 passed, 1 warning in 242.04s (0:04:02) ==================
poetry run ruff format .
36 files left unchanged
poetry run ruff check --fix
```

**Comment by danellecline** [comment]
No luck.  Tried rerunning  `just setup`, but hitting an error with netcdf4 now 
```
/D/c/pbpkeep (main 👍  ) dcline@ADA.shore.mbari.org🐠  j setup                                                                                                                                                                                                                                                                                                                                                                               (py11) 170ms  Tue Aug 27 11:30:22 2024
curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

The latest version (1.8.3) is already installed.
poetry install
Installing dependencies from lock file

Package operations: 88 installs, 19 updates, 0 removals

  - Downgrading certifi (2024.7.4 -> 2023.11.17)
  - Updating idna (3.7 -> 3.8)
  - Installing pyasn1 (0.6.0)
  - Installing pycparser (2.22)
  - Installing cachetools (5.5.0)
  - Installing cffi (1.17.0)
  - Installing iniconfig (2.0.0)
  - Installing more-itertools (10.4.0)
  - Installing pluggy (1.5.0)
  - Updating protobuf (4.25.3 -> 5.27.3)
  - Installing pyasn1-modules (0.4.0)
  - Installing rsa (4.7.2)
  - Downgrading scipy (1.14.0 -> 1.10.0)
  - Updating zipp (3.19.2 -> 3.20.1)
  - Installing audioread (3.0.1)
  - Installing coverage (7.6.1)
  - Installing crashtest (0.4.1)
  - Installing decorator (5.1.1)
  - Installing distlib (0.3.8)
  - Installing google-auth (2.34.0)
  - Installing googleapis-common-protos (1.64.0)
  - Updating imageio (2.34.2 -> 2.35.1)
  - Updating importlib-metadata (8.0.0 -> 8.4.0)
  - Installing jaraco-classes (3.4.0)
  - Installing locket (1.0.0)
  - Installing msgpack (1.0.8)
  - Downgrading networkx (3.3 -> 3.2.1)
  - Updating numba (0.57.0 -> 0.57.1)
  - Installing poetry-core (1.9.0)
  - Installing pooch (1.8.2)
  - Installing proto-plus (1.24.0)
  - Installing ptyprocess (0.7.0)
  - Updating pyparsing (3.1.2 -> 3.1.4)
  - Installing pyproject-hooks (1.1.0)
  - Installing pytest (7.4.4)
  - Downgrading python-dateutil (2.9.0.post0 -> 2.8.2)
  - Installing rapidfuzz (3.9.6)
  - Updating scikit-learn (1.4.0rc1 -> 1.5.1)
  - Installing soundfile (0.12.1)
  - Installing soxr (0.5.0)
  - Updating tifffile (2024.7.2 -> 2024.8.24)
  - Installing toolz (0.12.1)
  - Updating botocore (1.34.144 -> 1.34.162)
  - Installing build (1.2.1)
  - Installing cachecontrol (0.14.0)
  - Installing cftime (1.6.4)
  - Installing cleo (2.1.0)
  - Installing cloudpickle (3.0.0)
  - Installing dulwich (0.21.7)
  - Installing et-xmlfile (1.1.0)
  - Installing fastjsonschema (2.20.0)
  - Installing google-api-core (2.19.1)
  - Installing google-crc32c (1.5.0)
  - Installing installer (0.7.0)
  - Installing keyring (24.3.1)
  - Installing librosa (0.10.2.post1)
  - Installing mypy-extensions (1.0.0)
  - Updating matplotlib (3.7.0 -> 3.9.2)
  - Installing partd (1.4.2)
  - Installing pexpect (4.9.0)
  - Installing pkginfo (1.11.1)
  - Installing poetry-plugin-export (1.8.0)
  - Installing pytest-cov (4.1.0)
  - Installing resampy (0.4.3)
  - Installing shellingham (1.5.4)
  - Installing tomlkit (0.13.2)
  - Updating tqdm (4.66.4 -> 4.66.5)
  - Installing trove-classifiers (2024.7.2)
  - Installing virtualenv (20.26.3)
  - Installing xattr (1.1.0)
  - Installing colorama (0.4.6)
  - Installing cryptography (41.0.7)
  - Installing dask (2023.12.1)
  - Installing docutils (0.16)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.2)
  - Installing h5py (3.11.0)
  - Installing marshmallow (3.20.2)
  - Installing netcdf4 (1.7.1.post2): Preparing...
  - Installing netcdf4 (1.7.1.post2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  -L/opt/homebrew/Cellar/netcdf/4.9.2/lib -lnetcdf
  Package hdf5 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hdf5.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hdf5' found
  reading from setup.cfg...
  using nc-config...
  checking /opt/homebrew/Cellar/netcdf/4.9.2/include...
  hdf5 headers not found in /opt/homebrew/Cellar/netcdf/4.9.2/include
  nc-config did provide path to HDF5 headers, search standard locations...
      HDF5_DIR environment variable not set, checking some standard locations ..
  checking /Users/dcline/miniconda3/envs/py11/include...
  hdf5 headers not found in /Users/dcline/miniconda3/envs/py11/include
  checking /Users/dcline/miniconda3/envs/py11/Library/include...
  hdf5 headers not found in /Users/dcline/miniconda3/envs/py11/Library/include
  checking /Users/dcline/include...
  hdf5 headers not found in /Users/dcline/include
  checking /usr/local/include...
  hdf5 headers not found in /usr/local/include
  checking /sw/include...
  hdf5 headers not found in /sw/include
  checking /opt/include...
  hdf5 headers not found in /opt/include
  checking /opt/local/include...
  hdf5 headers not found in /opt/local/include
  checking /opt/homebrew/include...
  HDF5 library version: 1.12.2 headers found in /opt/homebrew/include
  HDF5 library version: 1.12.2 found in /opt/homebrew
  Traceback (most recent call last):
    File "/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
      from . import multiarray
    File "/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
      from . import overrides
    File "/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
      from numpy._core._multiarray_umath import (
  ImportError: dlopen(/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so, 0x0002): tried: '/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (no such file), '/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/private/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (no such file), '/private/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
  
```

**Comment by danellecline** [comment]
More specifically, seeing this error

```

  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
  
  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.
  
  We have compiled some common reasons and troubleshooting tips at:
  
      https://numpy.org/devdocs/user/troubleshooting-importerror.html
  
  Please note and check the following:
  
    * The Python version is: Python3.11 from "/var/folders/p8/dld1k4l14tg5fpljnb32tl9h0000k6/T/tmpu8ahpmii/.venv/bin/python"
    * The NumPy version is: "2.1.0"
```

**Comment by carueda** [comment]
Don't think I've ever seen that kind of error in the past. Sorry, I'm not sure what to suggest... ah (though your error seems completely unrelated with mypy), I note a little difference regarding `just setup` wrt the CI workflow (which is [successful](https://github.com/mbari-org/pbp/actions/runs/10565231208/job/29269308099) at this moment):  there is no `just install-types` step involved in CI (which is included in `just setup`). Maybe that explicit step is not really needed anymore as type-related dependencies were added to pyproject.toml...

**Comment by danellecline** [comment]
This has gone away.  I checked out the code to a new directory and this seems to be resolved. Perhaps something wonky in my Pycharm environment.
